### PR TITLE
mrpt_graphslam_2d package

### PR DESCRIPTION
**Pull request by bergercookie**
PR introduced a new ros wrapper utilizing the mrpt-graphslam library.

note: When launching the demo launchfile mind that the robot movement starts after ~20 seconds. Also in the current dataset only the laser scans are used (and not the odometry) as the robot odometry is problematic. 

@jlblancoc As always, your input on the code and the programming stye is hugely appreciated. :)

### CODE REVIEW

**Comment by jlblancoc** [comment]
Great! I'll test it soon...

Could you figure out why this is happening??
https://travis-ci.org/mrpt-ros-pkg/mrpt_slam/builds/169718222#L3075

Perhaps something missing in the CMake script??

**Comment by bergercookie** [comment]
>Perhaps something missing in the CMake script??

I think it is the missing catkin_INCLUDE_DIRS directive. The weird thing is that without it compiles successfully on my PC.

**Comment by bergercookie** [comment]
@jlblancoc I 've issued a [new PR](https://github.com/mrpt-ros-pkg/mrpt_navigation/pull/38) in mrpt_navigation repo. Could you trigger another travis rerun after the mrpt_navigation PR is merged?

**Comment by jlblancoc** [comment]
Done! https://travis-ci.org/mrpt-ros-pkg/mrpt_slam/builds/169724085

**Comment by bergercookie** [comment]
>mrpt::utils::map_traits_stdmap> >::getOccupancyGridMap2D(mrpt::maps::COccupancyGridMap2D*, mrpt::system::TTimeStamp*)’ m_graphslam_engine->getOccupancyGridMap2D(&mrpt_gridmap, &mrpt_time);

Ouch, this has to do with the change iof arguments in the corresponding mrpt-graphslam method. Making a PR for this as well, https://github.com/MRPT/mrpt/pull/357.

**Comment by bergercookie** [comment]
Hmm, I have already changed the definition of getOccupancyGridMap2D method in the mrpt repo with yesterday's PR there but still it finds the previous wrong method definition. @jlblancoc, may be that the github code takes some time to reflect to the PPA repositories?

**Comment by jlblancoc** [comment]
Yes, PPA has been a manual thing until now... 

But I've wanted for a long time to automate the whole thing and now it's finally done: from now on, PPAs will be generated every 8 hours if changes are detected.

And they're currently building right now so you don't have to wait until tomorrow for yesterday's changes... Cheers.

**Comment by bergercookie** [comment]
@jlblancoc [the error](https://travis-ci.org/mrpt-ros-pkg/mrpt_slam/builds/169978460) is in the lines of mrpt_macros.h. Could you figure out what this is about?

**Comment by jlblancoc** [comment]
It should be fixed now after https://github.com/MRPT/mrpt/commit/516e3a792240abc029230485483fa80c5167d8ba !!
Let's wait for the PPA to update... (sigh)

**Comment by jlblancoc** [comment]
Re-starting build in travis... https://travis-ci.org/mrpt-ros-pkg/mrpt_slam/builds/169978460

**Comment by jlblancoc** [comment]
oh! Travis relies on Trusty (14.04) and PPA failed for that version due to this bug: https://github.com/MRPT/mrpt/issues/358
We'll have to fix it first...

**Comment by jlblancoc** [comment]
At end! Travis is green.

**Comment by bergercookie** [comment]
Finally! :-)

**Pull request merged**
